### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eric-bunch**

### CODE REVIEW

**Comment by daniel-bolanos** [comment]
@nfriedly @germanattanasio can you please verify this is working in your Macs also? thank you

**Comment by nfriedly** [comment]
The `pip install` didn't seem to work for me. The first attempt errored with 

```
error: could not create '/Library/Python/2.7/site-packages/autobahn': Permission denied
```

Full log at http://pastebin.com/kZePUMZ2

I tried again with `sudo` and it got a little farther, but then ended with this:

```
  Running setup.py install for service-identity

  Found existing installation: six 1.4.1
    Uninstalling six:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/req.py", line 1089, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/req.py", line 476, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/req.py", line 1391, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.0-py2.7.egg/pip/util.py", line 248, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-AHsSAl-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Storing complete log in /Users/nfriedly/.pip/pip.log
```

Full log for that run at http://pastebin.com/VdzSjR6b

And, then, here is the pip.log file: http://pastebin.com/y8jRardg in case it has any additional useful info.

**Comment by eric-bunch** [comment]
Hmm. Is your pip up to date? And are you working in a virtual environment?

**Comment by nfriedly** [comment]
pip should be, I just installed it yesterday. And no, I was not using a virtual environment.

**Comment by nfriedly** [comment]
Actually, now that you mention it, I'm on pip v1.0 - the install script didn't seem to work for me, so I followed the install from source instructions and just noticed that they link to v1.0 in the v1.1 docs. Also, virtualenv doesn't seem to be working anymore, although I know I've used it before. I think my laptop may be about due for a wipe and reinstall...

**Comment by eric-bunch** [comment]
I see. I'm far from an expert at this kind of thing, but I found these two
answers for problems that seem similar to yours

http://stackoverflow.com/questions/7275295/how-do-i-write-a-setup-py-for-a-twistd-twisted-plugin-that-works-with-setuptools
http://serverfault.com/questions/358151/pip-install-carbon-looks-like-it-works-but-pip-disagrees-afterward

The second one seems easier to try first. But that is really strange about
your virtualenv no longer working. My instinct would be to upgrade pip, and
then upgrade/reinstall virtualenv.

**Pull request merged**
